"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


APP = ['SportsGrabber.py']
DATA_FILES = ['./back_button.gif','./baseball_hitter.gif','./baseball_pitcher.gif','./baseball.gif',
'./basketball.gif','./convert.gif','./men_basketball.gif','./men_soccer.gif','./open_doc.gif','./save_as.gif',
'./soccer.gif','./softball.gif','./volleyball.gif','./women_basketball.gif','./women_soccer.gif']
OPTIONS = {
            'argv_emulation': False,
            'includes': ['lxml.etree', 'lxml._elementpath']
        }

setup(
    console=['SportsGrabber.py'],
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
